---
- name: Configure Apache for WordPress
  ansible.builtin.template:
    src: wordpress.conf.j2
    dest: /etc/httpd/conf.d/wordpress.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache
