---
- name: Ensure all packages are installed (no upgrade)
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - php-fpm
      - php-json
      - php-gd
      - php-xml
      - php-mbstring
      - php-zip
      - wget
      - unzip
    state: present

- name: Start and enable services
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - httpd
    - php-fpm
