---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy WordPress files to web root
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes
    owner: apache
    group: apache
    mode: '0755'

- name: Set proper permissions for WordPress
  file:
    path: /var/www/html
    owner: apache
    group: apache
    mode: '0755'
    recurse: yes

- name: Create wp-config.php from template
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: apache
    group: apache
    mode: '0644'

- name: Remove default Apache welcome page
  file:
    path: /var/www/html/index.html
    state: absent

- name: Clean up downloaded files
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /tmp/wordpress.tar.gz
    - /tmp/wordpress
