---
- name: Download WordPress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: true

- name: Copy WordPress files to web root
  ansible.builtin.copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: true
    owner: apache
    group: apache
    mode: '0755'

- name: Set proper permissions for WordPress
  ansible.builtin.file:
    path: /var/www/html
    owner: apache
    group: apache
    mode: '0755'
    recurse: true

- name: Create wp-config.php from template
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: apache
    group: apache
    mode: '0644'

- name: Remove default Apache welcome page
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Clean up downloaded files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /tmp/wordpress.tar.gz
    - /tmp/wordpress
